// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/ybgr111/auth/internal/repository.LogRepository -o log_repository_minimock.go -n LogRepositoryMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	logModel "github.com/ybgr111/auth/internal/repository/log/model"
)

// LogRepositoryMock implements repository.LogRepository
type LogRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreate          func(ctx context.Context, log *logModel.Log) (err error)
	inspectFuncCreate   func(ctx context.Context, log *logModel.Log)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mLogRepositoryMockCreate
}

// NewLogRepositoryMock returns a mock for repository.LogRepository
func NewLogRepositoryMock(t minimock.Tester) *LogRepositoryMock {
	m := &LogRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mLogRepositoryMockCreate{mock: m}
	m.CreateMock.callArgs = []*LogRepositoryMockCreateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mLogRepositoryMockCreate struct {
	mock               *LogRepositoryMock
	defaultExpectation *LogRepositoryMockCreateExpectation
	expectations       []*LogRepositoryMockCreateExpectation

	callArgs []*LogRepositoryMockCreateParams
	mutex    sync.RWMutex
}

// LogRepositoryMockCreateExpectation specifies expectation struct of the LogRepository.Create
type LogRepositoryMockCreateExpectation struct {
	mock    *LogRepositoryMock
	params  *LogRepositoryMockCreateParams
	results *LogRepositoryMockCreateResults
	Counter uint64
}

// LogRepositoryMockCreateParams contains parameters of the LogRepository.Create
type LogRepositoryMockCreateParams struct {
	ctx context.Context
	log *logModel.Log
}

// LogRepositoryMockCreateResults contains results of the LogRepository.Create
type LogRepositoryMockCreateResults struct {
	err error
}

// Expect sets up expected params for LogRepository.Create
func (mmCreate *mLogRepositoryMockCreate) Expect(ctx context.Context, log *logModel.Log) *mLogRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("LogRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &LogRepositoryMockCreateExpectation{}
	}

	mmCreate.defaultExpectation.params = &LogRepositoryMockCreateParams{ctx, log}
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the LogRepository.Create
func (mmCreate *mLogRepositoryMockCreate) Inspect(f func(ctx context.Context, log *logModel.Log)) *mLogRepositoryMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for LogRepositoryMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by LogRepository.Create
func (mmCreate *mLogRepositoryMockCreate) Return(err error) *LogRepositoryMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("LogRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &LogRepositoryMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &LogRepositoryMockCreateResults{err}
	return mmCreate.mock
}

// Set uses given function f to mock the LogRepository.Create method
func (mmCreate *mLogRepositoryMockCreate) Set(f func(ctx context.Context, log *logModel.Log) (err error)) *LogRepositoryMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the LogRepository.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the LogRepository.Create method")
	}

	mmCreate.mock.funcCreate = f
	return mmCreate.mock
}

// When sets expectation for the LogRepository.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mLogRepositoryMockCreate) When(ctx context.Context, log *logModel.Log) *LogRepositoryMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("LogRepositoryMock.Create mock is already set by Set")
	}

	expectation := &LogRepositoryMockCreateExpectation{
		mock:   mmCreate.mock,
		params: &LogRepositoryMockCreateParams{ctx, log},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up LogRepository.Create return parameters for the expectation previously defined by the When method
func (e *LogRepositoryMockCreateExpectation) Then(err error) *LogRepositoryMock {
	e.results = &LogRepositoryMockCreateResults{err}
	return e.mock
}

// Create implements repository.LogRepository
func (mmCreate *LogRepositoryMock) Create(ctx context.Context, log *logModel.Log) (err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, log)
	}

	mm_params := LogRepositoryMockCreateParams{ctx, log}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, &mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_got := LogRepositoryMockCreateParams{ctx, log}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("LogRepositoryMock.Create got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the LogRepositoryMock.Create")
		}
		return (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, log)
	}
	mmCreate.t.Fatalf("Unexpected call to LogRepositoryMock.Create. %v %v", ctx, log)
	return
}

// CreateAfterCounter returns a count of finished LogRepositoryMock.Create invocations
func (mmCreate *LogRepositoryMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of LogRepositoryMock.Create invocations
func (mmCreate *LogRepositoryMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to LogRepositoryMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mLogRepositoryMockCreate) Calls() []*LogRepositoryMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*LogRepositoryMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *LogRepositoryMock) MinimockCreateDone() bool {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		return false
	}
	return true
}

// MinimockCreateInspect logs each unmet expectation
func (m *LogRepositoryMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LogRepositoryMock.Create with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to LogRepositoryMock.Create")
		} else {
			m.t.Errorf("Expected call to LogRepositoryMock.Create with params: %#v", *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		m.t.Error("Expected call to LogRepositoryMock.Create")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LogRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateInspect()
			m.t.FailNow()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LogRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LogRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone()
}
